import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns
data = pd. read_csv ('/content/covid data.csv' )
plt.figure (figsize=(10, 6))
sns.scatterplot (x='TotalCases', y='TotalDeaths', data=data)
plt.title( 'Total Deaths vs Total Cases' ) 
plt.xlabel ( 'Total Cases')
plt.ylabel ( 'Total Deaths')
plt.show()
top_countries = data.sort_values(by='TotalCases', ascending=False) head (10)
plt.figure(figsize=(12, 6))
sns.barplot(x='Country/Region', y='TotalCases', data=top_countries)
plt.title( 'Top 10 Countries by Total Cases') 
plt.xlabel ('Country/Region' ) 
plt.ylabel ( 'Total Cases')
plt.xticks (rotation=45)
plt.show ()
correlation _matrix = data.corr)
plt.figure(figsize=(10, 8))
sns. heatmap (correlation_matrix, annot=True, cmap=' coolwarm' )
plt.title( 'Correlation Matrix')
plt.show ()
